### ISSUE TITLE
pcb source available?

### ISSUE THREAD

**Issue by fugounashi** [larrbo/odd-rocket#1]
Hi,

Just came across your 5plit boards and it's basically what I've started designing myself (pcb sized for cheapness, promicro on top for thickness, 5x3 plus thumbs) but as well as a pcb mount choc version like you have I also want to make an mx version with plates.  If you are interested in sharing your pcb source files I'd like to try to make my modified version.

Thanks!

**Comment by larrbo** [comment]
I have the project on easyeda. If you have an account I can share it with you.

**Comment by fugounashi** [comment]
awesome, thanks, I just created an account: fugounashi
